"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HEARTBEAT_INTERVAL_SECONDS_MIN_VALUE = exports.HEARTBEAT_INTERVAL_SECONDS_DEFAULT = exports.MINIMUM_IDLE_QUEUE_RETENTION_PERIOD_SECONDS = exports.IDLE_QUEUE_RETENTION_PERIOD = exports.VIRTUAL_QUEUE_HOST_QUEUE_ATTRIBUTE = exports.RESPONSE_QUEUE_URL_ATTRIBUTE_NAME = void 0;
exports.RESPONSE_QUEUE_URL_ATTRIBUTE_NAME = 'ResponseQueueUrl';
exports.VIRTUAL_QUEUE_HOST_QUEUE_ATTRIBUTE = 'HostQueueUrl';
exports.IDLE_QUEUE_RETENTION_PERIOD = 'IdleQueueRetentionPeriodSeconds';
exports.MINIMUM_IDLE_QUEUE_RETENTION_PERIOD_SECONDS = 1;
exports.HEARTBEAT_INTERVAL_SECONDS_DEFAULT = 5;
exports.HEARTBEAT_INTERVAL_SECONDS_MIN_VALUE = 1;
