export const RESPONSE_QUEUE_URL_ATTRIBUTE_NAME = 'ResponseQueueUrl';
export const VIRTUAL_QUEUE_HOST_QUEUE_ATTRIBUTE = 'HostQueueUrl';
export const IDLE_QUEUE_RETENTION_PERIOD = 'IdleQueueRetentionPeriodSeconds';
export const MINIMUM_IDLE_QUEUE_RETENTION_PERIOD_SECONDS = 1;
export const HEARTBEAT_INTERVAL_SECONDS_DEFAULT = 5;
export const HEARTBEAT_INTERVAL_SECONDS_MIN_VALUE = 1;
